// CI STUB — placeholder values only, no real credentials.
//
// The real lib/firebase_options.dart is generated by `flutterfire configure`
// and is gitignored. CI copies this file into place so that `flutter analyze`,
// `flutter test`, and compile-only builds have something to resolve against.
//
// An artifact built with these values cannot talk to Firebase and must never be
// distributed. Release workflows inject the real config from secrets instead.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'ci-stub-api-key',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-stub-project',
    authDomain: 'ci-stub-project.firebaseapp.com',
    storageBucket: 'ci-stub-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'ci-stub-api-key',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-stub-project',
    storageBucket: 'ci-stub-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'ci-stub-api-key',
    appId: '1:000000000000:ios:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'ci-stub-project',
    storageBucket: 'ci-stub-project.firebasestorage.app',
    iosBundleId: 'com.healthcare.healthcareMobile',
  );
}
