import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'app.dart';
import 'core/config/app_config.dart';
import 'core/observability/crash_reporting.dart';
import 'core/providers.dart';
import 'core/session/onboarding_controller.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final results = await Future.wait([
    Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform),
    SharedPreferences.getInstance(),
  ]);
  final prefs = results[1] as SharedPreferences;

  // Installed before the first frame so an error during startup is reported
  // rather than lost. Nothing user-identifying or clinical is ever forwarded —
  // see `CrashReporting`.
  await CrashReporting.initialise(AppConfig.fromEnvironment());

  // One-time cleanup of clinical data written to plaintext SharedPreferences by
  // earlier builds. Runs before the first frame so no screen can read it.
  final purged = await purgeLegacyHealthData(prefs);
  if (kDebugMode && purged > 0) {
    debugPrint('Removed $purged legacy plaintext health key(s).');
  }

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        appVersionProvider.overrideWithValue('0.1.0'),
      ],
      child: const MiDoctorApp(),
    ),
  );
}
