import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'admin/admin_app.dart';
import 'core/config/app_config.dart';
import 'core/observability/crash_reporting.dart';
import 'core/providers.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure`

/// Entry point for the MiDoctor operator console.
///
///   flutter run -d chrome -t lib/main_admin.dart
///   flutter build web -t lib/main_admin.dart --release \
///     --dart-define=USE_FIXTURES=false \
///     --dart-define=API_BASE_URL=https://asia-south1-<project>.cloudfunctions.net/api
///
/// Separate from `lib/main.dart` on purpose. Nothing under `lib/admin/` is
/// reachable from the mobile entry point, so approval logic and reviewer copy
/// are not compiled into the binary that ships to the people being reviewed —
/// and the console can be deployed behind a VPN or an IdP without any of that
/// touching the app.
///
/// It deliberately does **not** run `purgeLegacyHealthData`: that migration
/// clears a patient's own device, and an operator's browser never held any.
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  final results = await Future.wait([
    Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform),
    SharedPreferences.getInstance(),
  ]);
  final prefs = results[1] as SharedPreferences;

  await CrashReporting.initialise(AppConfig.fromEnvironment());

  runApp(
    ProviderScope(
      overrides: [
        sharedPreferencesProvider.overrideWithValue(prefs),
        appVersionProvider.overrideWithValue('0.1.0'),
      ],
      child: const MiDoctorAdminApp(),
    ),
  );
}
